2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_setup.py:_flush():67] Configure stats pid to 58823
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_setup.py:_flush():67] Loading settings from /Users/tawneykirkland/.config/wandb/settings
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_setup.py:_flush():67] Loading settings from /Users/tawneykirkland/credit/modeling/wandb/settings
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/tawneykirkland/credit/modeling/wandb/run-20250302_154616-mgdswef9/logs/debug.log
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/tawneykirkland/credit/modeling/wandb/run-20250302_154616-mgdswef9/logs/debug-internal.log
2025-03-02 15:46:16,509 INFO    MainThread:58823 [wandb_init.py:init():761] calling init triggers
2025-03-02 15:46:16,510 INFO    MainThread:58823 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'n_estimators': 100, 'max_depth': 10, 'test_size': 0.25, 'random_state': 12, '_wandb': {}}
2025-03-02 15:46:16,510 INFO    MainThread:58823 [wandb_init.py:init():784] starting backend
2025-03-02 15:46:16,510 INFO    MainThread:58823 [wandb_init.py:init():788] sending inform_init request
2025-03-02 15:46:16,550 INFO    MainThread:58823 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-02 15:46:16,550 INFO    MainThread:58823 [wandb_init.py:init():803] backend started and connected
2025-03-02 15:46:16,553 INFO    MainThread:58823 [wandb_init.py:init():896] updated telemetry
2025-03-02 15:46:16,567 INFO    MainThread:58823 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 15:46:16,895 INFO    MainThread:58823 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 15:46:16,970 INFO    MainThread:58823 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 15:46:16,970 INFO    MainThread:58823 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 15:46:16,970 INFO    MainThread:58823 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 15:46:16,970 INFO    MainThread:58823 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 15:46:16,972 INFO    MainThread:58823 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 15:46:43,822 INFO    MainThread:58823 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'viz', 'confusion_matrix') {'id': 'wandb/confusion_matrix/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'confusion_matrix'}} None
2025-03-02 15:46:44,292 INFO    MainThread:58823 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'roc') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/area-under-curve/v0', 'fieldSettings': {'x': 'fpr', 'y': 'tpr', 'class': 'class'}, 'stringSettings': {'title': 'ROC Curve', 'x-axis-title': 'False positive rate', 'y-axis-title': 'True positive rate'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'roc_table'}], 'fields': []}]}]}}} None
2025-03-02 15:46:44,577 INFO    MainThread:58823 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'precision_recall') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/area-under-curve/v0', 'fieldSettings': {'x': 'recall', 'y': 'precision', 'class': 'class'}, 'stringSettings': {'title': 'Precision-Recall Curve', 'x-axis-title': 'Recall', 'y-axis-title': 'Precision'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'precision_recall_table'}], 'fields': []}]}]}}} None
2025-03-02 15:46:44,764 INFO    MainThread:58823 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'viz', 'class_proportions') {'id': 'wandb/class_proportions/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'class_proportions'}} None
2025-03-02 15:46:50,353 WARNING MsgRouterThr:58823 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 15:46:50,357 INFO    MsgRouterThr:58823 [mailbox.py:close():115] Closing mailbox, abandoning 6 handles.
